// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jfvnedehksmxlyrmsnzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmdm5lZGVoa3NteGx5cm1zbnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODY0ODAsImV4cCI6MjA3MjY2MjQ4MH0.LycPMEjiXsuaWLkoMcKe0hKwsRrlFS3qPnpIob0ZtEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);